# Generated by Django 4.2.5 on 2023-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('date_time', models.DateTimeField(verbose_name='Date Time')),
                ('location', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('max_participants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='participants')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('event', models.ManyToManyField(to='cpanel.event')),
            ],
        ),
    ]
