# Generated by Django 4.2.5 on 2023-09-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0005_remove_event_event_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
