# Generated by Django 4.2.5 on 2023-09-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0007_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='cpanel.eventtype'),
            preserve_default=False,
        ),
    ]
