# Generated by Django 4.2.5 on 2023-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0012_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='session_token',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
