# Generated by Django 4.2.5 on 2023-09-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0013_participant_password_participant_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
