# Generated by Django 4.2.5 on 2023-09-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0015_alter_participant_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, default='no-photo.jpg', null=True, upload_to='events'),
        ),
    ]
