# Generated by Django 4.2.5 on 2023-09-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0016_event_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, default='events/no-photo.jpg', null=True, upload_to='participants'),
        ),
    ]
