# Generated by Django 4.2.5 on 2023-09-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0017_alter_participant_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, default='events/no-photo.jpg', null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, default='participants/no-photo.jpg', null=True, upload_to='participants'),
        ),
    ]
